console.log("charAt(): ", "hello world".charAt(6) === 'w');
console.log("charCodeAt(): ", "hello world".charCodeAt(6));
console.log("codePointAt(): ", "\ud83d\udc99".codePointAt(0));
console.log("codePointAt(): ", "\ud83d\udc99".codePointAt(1));
console.log("concat(): ", "hello ".concat("world"));
console.log("endsWith(): ", "hello world".endsWith("orld"));
console.log("fromCharCode(): ", String.fromCharCode(64, 0xd83d));
console.log("fromCodePoint(): ", String.fromCodePoint(0xd83d, 0xdc99));
console.log("includes(): ", "hello world".includes("o w"));
console.log("indexOf(): ", "hello world".indexOf("o"));
console.log("lastIndexOf(): ", "hello world".lastIndexOf("o"));
console.log("localeCompare(): ", "hellö world".localeCompare("hello"));
console.log("match(): ", "hello world".match("ll"));
console.log("matchAll(): ", "hello world".matchAll("o"));
console.log("normalize(): ", "hello world".normalize());
console.log("padEnd(): ", "hello world".padEnd(20, "!"));
console.log("padStart(): ", "hello world".padStart(20, ">"));
console.log("repeat(): ", "hello world".repeat(3));
console.log("replace(): ", "hello world".replace("world", "ape"));
console.log("replaceAll(): ", "hello world".replaceAll("o", "ö"));
console.log("search(): ", "hello world".search("o"));
console.log("slice(): ", "hello world".slice(5,8));
console.log("split(): ", "hello world".split("o"));
console.log("startsWith(): ", "hello world".startsWith("hell"));
console.log("substring(): ", "hello world".substring(3, 5));
console.log("toLocaleLowerCase(): ", "HELLÖ world".toLocaleLowerCase());
console.log("toLocaleUpperCase(): ", "HELLO world".toLocaleUpperCase());
console.log("toLowerCase(): ", "HELLÖ world".toLowerCase());
console.log("toUpperCase(): ", "hello wörld".toUpperCase());
console.log("trim(): ", "   hello world   ".trim());
console.log("trimEnd(): ", "   hello world    ".trimEnd());
console.log("trimStart(): ", "   hello world   ".trimStart());
console.log("valueOf(): ", "5".valueOf());
